import type { Metadata } from "next";
import "./globals.css";
import { ProposalProvider } from '../context/ProposalContext';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body>
        <ProposalProvider>
          {children}
        </ProposalProvider>
      </body>
    </html>
  );
} 